[package]
name = "qml"
version = "0.1.0"
authors = ["Tyler Pickett <t.pickett66@gmail.com>"]
license = "MIT/Apache-2.0"

build = "build.rs"

[dependencies]
libc = "^0.2.6"
lazy_static = "^0.1.0"

[build-dependencies]
pkg-config = "^0.3.6"
